serviceProperties :
    serviceDataProperites:
        serviceName : "collection"
        ip : "localhost"
        port : 8082
        rootUrl : "/collection"
    zNodeInfoProperites:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "192.168.56.17:2181"

tomcatPort : 8082

endpoints.shutdown.enabled : true