serviceProperties:
    serviceDataProperties:
        serviceName : "collection_B"
        ip : "172.18.0.32"
        port : 8102
        rootUrl : "/collection"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191,172.18.0.12:2192,172.18.0.13:2193"

tomcatPort: 8102