serviceProperties:
    serviceDataProperites:
        serviceName : "collection_A"
        ip : "172.18.0.31"
        port : 8101
        rootUrl : "/collection"
    zNodeInfoProperites:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191,172.18.0.12:2192,172.18.0.13:2193"

tomcatPort: 8101