serviceProperties :
    serviceDataProperties:
        serviceGroupName : "collection"
        serviceName : "collection_standalone"
        ip : "172.18.0.31"
        port : 8101
        rootUrl : "/collection"
        topicInfo : "{\"producers\":[\"aggregationTopic\"]}"
    zNodeInfoProperties:
        confZnodePath : "/confManageNode"
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191"

tomcatPort: 8101

logging.file : "/opt/collection/log/console.log"