serviceProperties:
    serviceDataProperties:
        serviceName : "ServiceC"
        ip : "172.18.0.33"
        port : 8103
        rootUrl : "/collection"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "192.168.56.17:2181"
    kafkaProducerProperties:
        brokerList : "192.168.56.17:9092"
        serializerClass : "org.apache.kafka.common.serialization.StringSerializer"
        batchSize : "200"
        retries : "0"
        maxBlockMs : "5000"

tomcatPort : 8103