tomcatPort : 8103

serviceProperties:
    serviceDataProperites:
        serviceName : "ServiceC"
        ip : "172.18.0.33"
        port : 8103
        rootUrl : "/collection"
    zNodeInfoProperites:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.21:2191,172.18.0.22:2192,172.18.0.23:2193"