serviceProperties :
    serviceDataProperties:
        serviceGroupName : "collection"
        serviceName : "collection_1"
        ip : "localhost"
        port : 8082
        rootUrl : "/collection"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "192.168.56.17:2181"
    kafkaProducerProperties:
        cacheTopic:
            brokerList : "192.168.56.17:9092"
            serializerClass : "org.apache.kafka.common.serialization.StringSerializer"
            batchSize : "200"
            retries : "0"
            maxBlockMs : "5000"

tomcatPort : 8082

endpoints.shutdown.enabled : true